AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: S3 Lambda Application

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: python3.11
    Architectures:
      - arm64
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: INFO
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: S3Application
        AWS_REGION_NAME: ap-northeast-1

Parameters:
  OverridesParam:
    Type: String
    Description: OverridesParam

Resources:
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: CommonLayer
      Description: Common Layer
      ContentUri: common_layer/
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.11
      BuildArchitecture: arm64

  S3LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      CodeUri: src/s3_lambda_functions/
      Description: S3 Lambda function
      Layers:
        - !Ref CommonLayer
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetObject
            Resource:
              - !Sub "arn:aws:s3:::lambda-bucket-${OverridesParam}"
              - !Sub "arn:aws:s3:::lambda-bucket-${OverridesParam}/*"
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref S3LambdaBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: public/
      Tags:
        Name: "s3-lambda-function"
      Timeout: 300

  LambdaInvokePermissionForS3:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt S3LambdaFunction.Arn
      Action: "lambda:InvokeFunction"
      Principal: "s3.amazonaws.com"
      SourceArn: !GetAtt S3LambdaBucket.Arn

  S3LambdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "lambda-bucket-${OverridesParam}"